name: Lint

on: [ push, pull_request ]

jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Vint
        run: pip install vim-vint=0.3.21

      - name: Run Vint
        run: vint --style-problem --color --stat vimrc
