name: Lint

on: [ push, pull_request ]

jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Vint
        uses: ludvighz/vint-action@v1
        with:
          path: vimrc
          args: --style-problem --color
